services:
  - type: web
    name: baseerah-backend
    env: docker
    plan: free
    dockerfilePath: backend/Dockerfile
    buildCommand: ""
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port 8000"

  - type: web
    name: baseerah-frontend
    env: static
    buildCommand: "cd frontend && npm install && npm run build"
    staticPublishPath: frontend/dist
